config/routes.rb
Rails.application.routes.draw do

  root 'users#upload'

  resources :users do
    collection do
      post :upload_csv
      get :upload
      get :download_csv
      post :assign_santas
      get :get_santas
    end
  end

end

app/models/csv_reader.rb
#for reading user input csv
class CsvReader

	def initialize(csv_text)
		begin
			@csv = CSV.parse(csv_text, :headers => true)
		rescue CSV::MalformedCSVError #check for malformed csv
			@error = true
		end
	end

	#CSV format is 2 columns (name, partner name)
	def process_names
		return false if @error
		User.delete_all #resets participants when you upload csv
		0.upto(@csv.count-1) do |row|
			user_name = @csv[row][0].presence
			next if user_name.nil? #skip bad csv input (no name)

			user = User.find_or_create_by(name: user_name.strip) #make user, prevent duplicate entry

			partner_name = @csv[row][1].presence
			next if partner_name.nil? 

			User.find_or_create_by(name: partner_name.strip, partner: user) #create partner
		end

		return true
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :secret_santa, :class_name => 'User'
	belongs_to :previous_secret_santa, :class_name => 'User'
	belongs_to :partner, :class_name => 'User'

	validates_presence_of :name
	validates_uniqueness_of :name, :case_sensitive => false #name uniqueness is not case sensitive
	validates_uniqueness_of :secret_santa_id, :allow_nil => true #can only have 1 santa
	validate :new_santa_constraint #custom validation

	accepts_nested_attributes_for :partner, :reject_if => lambda { |x| x[:name].blank? } #do not create if nest is not filled up

	scope :active, -> { where(active: true) } #active means people who want to participate in next secret santa
	scope :possible_santas, lambda { |user|  #all possible santas (not partner, not self, not previous)
		active.where('id not in (?)', [user.id, user.previous_secret_santa_id, user.partner_id].reject(&:nil?))
	}
	scope :available_possible_santas, lambda { |user| #all possible santas (not partner, not self, not previous), who are not yet taken by other people
		active.where('id not in (?)', (User.pluck(:secret_santa_id) + [user.id, user.previous_secret_santa_id, user.partner_id]).uniq.reject(&:nil?))
	}

	after_create :update_partner #callback so partner's partner_id is also updated

	#custom validation
	def new_santa_constraint
		if secret_santa_id #validation only happens when a secret santa is assigned/present
			#make sure new santa is not same as old santa
			if previous_secret_santa_id && previous_secret_santa_id == secret_santa_id
				errors.add(:secret_santa_id, "can't be same as previous")
			end

			#make sure santa is not same as partner
			if partner_id && partner_id == secret_santa_id
				errors.add(:secret_santa_id, "can't be same as partner")
			end

			#for creation on nested attribute; make sure name and partner name is not the same
			if partner && partner.try(:name) == name
				errors.add(:name, "cannot have the same name as partner")
			end
		end
	end

	#callback so partner's partner_id is also updated
	def update_partner
		partner.update(partner_id: self.id) if partner
	end

	def partner_name
		partner.try(:name)
	end

	#giftee is the one you're supposed to give a gift to
	def previous_giftee
		User.find_by(previous_secret_santa_id: self.id).try(:name)
	end

	def current_giftee
		User.find_by(secret_santa_id: self.id).try(:name)
	end

	#assign a santa based on the 3 constraints
	def assign_santa
		#get random santa from available valid santa pool
		random_santa = User.available_possible_santas(self).order("RANDOM()").limit(1).first
		
		if random_santa
			self.update(secret_santa: random_santa) #take if found one
			return true
		#if no valid santa is found
		else
			#if there is only 3 or less people participating, no possible values can be made anymore
			if User.active.count > 3
				possible_santa = User.possible_santas(self).order("RANDOM()").limit(1).first #get possible santa, even if taken
				user = User.find_by(secret_santa: possible_santa) #get user who has that santa
				user.update(secret_santa_id: nil) #remove person's santa
				self.update(secret_santa: possible_santa) #put it in current user's santa
				user.assign_santa #newly "orphaned" user is assigned a santa

				return true #everyone has found a valid match
			else
				return false #finding a partner for all has failed
			end
		end
	end

	#every new round, transfer previous santa to other column and make secrent_santa column available
	def self.prepare_for_new_santas
		sql = "UPDATE users SET previous_secret_santa_id = secret_santa_id, secret_santa_id = NULL"
		ActiveRecord::Base.connection.execute(sql)
	end

	#method for assigning valid santa to everyone
	def self.assign_secret_santas

		return {status: :error, message: "No participants yet!"} if User.active.count==0
		#catch exception in transaction (when no valid combination is possible)
		begin
			User.transaction do #use transaction so rollback is possible for a failed round
				User.prepare_for_new_santas			
				User.active.order("RANDOM()").each do |user|
					success = user.assign_santa

					if !success
						raise("Cannot create any more valid combination.") #possible failure for <= 3 participants
					end
				end
			end
		rescue RuntimeError => e
			msg = {status: :error, message: e.message}
		else
			msg = {status: :success, message: "Success! Check out the participant list page to see your new giftee."}
		end

		return msg
	end

	#returns a summary of User table
	def self.get_summary_csv
		str = ["Name", "Partner Name", "Previous Secret Santa", "Current Secret Santa", "Previous Giftee", "Current Giftee"].join(",") + "\n" 
		#look by batch in case of high user volume
		User.find_each(batch_size: 1000) do |user| 
		  str << [user.name,user.partner_name, user.previous_secret_santa.try(:name), user.secret_santa.try(:name), user.previous_giftee, user.current_giftee].map{|x| "\"#{x}\""}.join(",")+"\n"  
		end

		return str
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
require 'csv' #for generating csv

class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update]

	def index
	  @users = User.all
	end

	def new
	  @user = User.new
	end

	def create
		@user = User.new(user_params)

	  	if @user.save
	  		msg = "Participant #{@user.name} added."
	  		msg = "Participants #{@user.name} & #{@user.partner_name} added." if @user.partner
	  		flash[:success] = msg
	  		redirect_to user_path(@user)
	  	else
	  		render :new
	  	end
	end

	def update
	    if @user.update(user_params)
	  		flash[:success] = "Participant details updated."
	  		redirect_to user_path(@user)
	  	else
	  		render :edit
	  	end
	end

	#user input CSV. Format: 1st column is name, 2nd column is partner name, not case sensitive
	def upload_csv
		csv_text = open(params[:file].tempfile).read
		success = CsvReader.new(csv_text).process_names

		if success
			flash[:success] = "Successfully uploaded new list of participants."
			redirect_to users_path
		else
			flash[:error] = "Bad CSV uploaded. Please try another"
			redirect_to root_path
		end
	end

	def assign_santas
		result = User.assign_secret_santas
		flash[result[:status]] = result[:message]

		redirect_to get_santas_users_path
	end

	#for downloading user database summary
	def download_csv
		str = User.get_summary_csv

		send_data str, :filename => "participants_summary_#{Time.now.to_i}.csv", :type => "text/csv"
	end

	private 
	  	def set_user
	  		@user = User.find(params[:id])
	  	end

	  	def user_params
	  		params.require(:user).permit(:name, :active, partner_attributes: [:name])
	  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(flash_type)
		{ :success => 'alert-success',
			:error => 'alert-danger',
			:alert => 'alert-warning',
			:notice => 'alert-info'
		}[flash_type.to_sym] || flash_type.to_s
	end

end

app/views/application/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <% if message.is_a?(Array) %>
      <%= message.join("<br/>").html_safe %>
    <% else %>
      <%= message %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>SecretSanta</title>
    <%= stylesheet_link_tag    'application', params[:controller], media: 'all'%>
    <%= javascript_include_tag 'application', params[:controller]%>
	  <%= csrf_meta_tags %>	
    <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="turbolinks-cache-control" content="no-cache">
  </head>

  <body class="overflow-hidden">
 	<!-- for pluggable_js -->
  	<%= javascript_pluggable_tag %>
   
    <div id="wrapper" class="preload">
      <!-- Top Nav -->
      <div id="top-nav" class="skin-6 fixed">
        <div class="brand">
            SecretSanta
        </div><!-- /brand -->
      	<div class="brand-overlay">
      		
      	</div>
    
      </div>
   

      <!-- Sidebar -->
      <aside class="fixed skin-6">
      	<div class="sidebar-overlay"></div>
          <div class="sidebar-inner scrollable-sidebar" id="sidebar-scroll">
           
          
            <!-- Menu -->
            <div class="main-menu">
              <ul>
                <li class="upload_users_menu">
                  <a href="<%= upload_users_path %>">
                    <i class="fa fa-upload dashboard_icon"></i>
                    <span class="text">
                      Upload New List
                    </span>
                    <span class="menu-hover"></span>
                  </a>
                </li>

                <li class="users_menu">
                  <a href="<%= users_path %>">
                    <i class="fa fa-list dashboard_icon"></i>
                    <span class="text">
                      Participants List
                    </span>
                    <span class="menu-hover"></span>
                  </a>
                </li>

                <li class="get_santas_menu">
                  <a href="<%= get_santas_users_path %>">
                    <i class="fa fa-gift dashboard_icon"></i>
                    <span class="text">
                      Start Secret Santa
                    </span>
                    <span class="menu-hover"></span>
                  </a>
                </li>
            
              </ul>
            </div><!-- /main-menu -->
          </div><!-- /sidebar-inner scrollable-sidebar -->

      </aside> <!-- /sidebar -->

      <div class="topper">
        <div class="row">
        <div class="col-sm-12 text-center">
          <p class="no-margin">
            Redecio R. 2017
          </p>
        </div><!-- /.col -->
      </div><!-- /.row-->
      </div>
      <div id="main-container">
        <div class="padding-md">
          <%= yield %>
        </div><!-- /.padding -->
      </div><!-- /main-container -->

    </div><!-- /wrapper -->

    
  </body>
</html>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="flash_div">
      <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |message| %>
          <div class="alert alert-danger fade in">
            <button class="close" data-dismiss="alert">×</button>
            <%= message %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="panel panel-default">
      <%= form_for @user, :html => { :class => 'form-horizontal', :"novalidate" => "",  :autocomplete => :off } do |f| %>
        <div class="panel-heading">
          <strong>User Form</strong>
        </div>
        <div class="panel-body">
          <% if ["new","create"].include?(params[:action]) %>
            <div class="form-group">
              <%= f.label :name, "Name", :class => 'control-label col-lg-3' %>
              <div class="col-lg-3">
                <%= f.text_field :name, :class => 'form-control input-sm', required: true %>
              </div>
            </div>
            <%= f.fields_for :partner, User.new do |user| %>
            <div class="form-group">
              <label class="col-lg-3 control-label">Partner Name</label>
              <div class="col-lg-3">
                <%= user.text_field :name, :class => 'form-control input-sm', placeholder: 'Leave blank if none', required: false %>
              </div>
            </div>
            <% end %>
        
          <% else %>
            <div class="form-group">
              <label class="col-lg-3 control-label">Name</label>
                <div class="col-lg-9">
                  <p class="form-control-static"><%= @user.name %></p>
                </div>
            </div>
            <div class="form-group">
              <label class="col-lg-3 control-label">Partner Name</label>
                <div class="col-lg-9">
                  <p class="form-control-static"><%= @user.partner_name %></p>
                </div>
            </div>
          <% end %>

          <!-- only allow to edit participating for users -->
          <% if ["edit","update"].include?(params[:action]) %>
          <div class="form-group">
            <%= f.label :active, "Participating?", :class => 'control-label col-lg-3' %>
            <div class="col-lg-5">
              <%= f.check_box :active, {:class => 'form-control input-sm'}, "true", "false" %>
            </div>
          </div>
          <% end %>

        </div>
        <div class="panel-footer text-right">
          <%= f.button type: :submit, :class => 'btn btn-fill btn-success' do %>
            <i class="fa fa-thumbs-up"></i> Save User
          <% end %>
          <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              users_path, :class => 'btn btn-fill btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h3 class="headline m-top-md">
  Edit User
  <span class="line"></span>
</h3>

<%= render :partial => 'form' %>

app/views/users/get_santas.html.erb
<h3 class="headline m-top-md">
  Start Secret Santa
  <span class="line"></span>
</h3>

<div class="row">
  <div class="col-md-12">
    <div class="flash_div">
      <%= render 'flash_messages', flash: flash %>
    </div>
<%= form_tag assign_santas_users_path, method: :post, class: "form-horizontal" do %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>Ready? <i class="fa fa-gift"></i></strong>
      </div>
      <div class="panel-body">	
	    <div class="form-group">
		  
		  <div class="col-lg-5">
		  Playing with <%= pluralize(User.active.count, 'participants')%>!<br><br>
		   Constraints: <br>
		   -You can't be your own Santa. <br>
		   -You can't be assigned the same Santa from last time.<br>
		   -You can't be your partner's Santa.
		  </div>
		</div>
	

		<div class="form-group">
	     
	      <div class="col-lg-3">
	        <%= button_tag type: "submit", :class => 'btn btn-info btn-fill' do %>
	            Start!
	        <% end %>
	      </div>
	    </div> 
      </div>
  	</div>

  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h3 class="headline m-top-md">
  Participants
  <span class="line"></span>
</h3>

<div class="row">
  <div class="col-md-12">
    <div class="flash_div">
      <%= render 'flash_messages', flash: flash %>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>List of Participants</strong>
      </div>
      <div class="panel-body">
        <table class="table table-striped data-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Partner Name</th>
              <th>Participating</th>
              <th>Actions</th>
            </tr> 
          </thead>
          
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= link_to user.name, user %></td>
                <td><%= user.partner_name %></td>
                <td><%= user.active? ? "Yes" : "No" %></td>
                <td class="actions">
                  <%= link_to edit_user_path(user), class:"btn btn-default btn-xs" do %>
                    <i class="fa fa-edit"></i> Edit
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>  
        </table>
      </div>
      <div class="panel-footer">
        <%= link_to download_csv_users_path, :class => 'btn btn-warning btn-fill', target: "_blank" do %>
            <i class="fa fa-download"></i> Download Participant Details Summary
        <% end %>
        <div class="pull-right">
          <%= link_to new_user_path, class: "btn btn-fill btn-success" do %>
            <i class="fa fa-plus"></i> Add Participant
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h3 class="headline m-top-md">
  Add new participant
  <span class="line"></span>
</h3>

<div class="flash_div">
  <%= render 'flash_messages', flash: flash %>
</div>

<%= render :partial => 'form' %>

app/views/users/show.html.erb
<h3 class="headline m-top-md">
  Participant
  <span class="line"></span>
</h3>
<div class="row">
  <div class="col-md-12">
    <div class="flash_div">
      <%= render 'flash_messages', flash: flash %>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>General Details</strong>
      </div>
      <div class="panel-body">
        <fieldset class="form-horizontal form-border">
          <div class="form-group">
            <label class="col-lg-3 control-label">Name</label>
            <div class="col-lg-9">
              <p class="form-control-static"><%= @user.name %></p>
            </div><!-- /.col -->
          </div><!-- /form-group -->

          <div class="form-group">
            <label class="col-lg-3 control-label">Partner Name</label>
            <div class="col-lg-9">
              <p class="form-control-static"><%= @user.partner_name %></p>
            </div><!-- /.col -->
          </div><!-- /form-group -->

          <div class="form-group">
            <label class="col-lg-3 control-label">Previous Giftee</label>
            <div class="col-lg-9">
              <p class="form-control-static"><%= @user.previous_giftee %></p>
            </div><!-- /.col -->
          </div><!-- /form-group -->

          <div class="form-group">
            <label class="col-lg-3 control-label">Current Giftee</label>
            <div class="col-lg-3">
              <p class="form-control-static spoiler"><%= @user.current_giftee %></p>
            </div><!-- /.col -->
            <div class="col-lg-3 no-left-pad">
              <p class="form-control-static help-text">(Hover to see)</p>
            </div><!-- /.col -->
          </div><!-- /form-group -->

          <div class="form-group">
            <label class="col-lg-3 control-label">Participating?</label>
            <div class="col-lg-9">
              <p class="form-control-static"><%= @user.active? ? "Yes" : "No" %></p>
            </div><!-- /.col -->
          </div><!-- /form-group -->
        </fieldset>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="padding-md">
        <%= link_to users_path, class: "btn btn-fill btn-default" do %>
          <i class="fa fa-list"></i> Back to Participants List
        <% end %>
        <div class="pull-right">
          <%= link_to edit_user_path(@user), class: "btn btn-fill btn-default" do %>
            <i class="fa fa-edit"></i> Edit
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/upload.html.erb
<h3 class="headline m-top-md">
  Upload List
  <span class="line"></span>
</h3>

<div class="row">
  <div class="col-md-12">
    <div class="flash_div">
      <%= render 'flash_messages', flash: flash %>
    </div>
<%= form_tag upload_csv_users_path, method: :post, class: "form-horizontal",
  multipart: true,  :autocomplete => :off do %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>Upload new set of participants</strong>
      </div>
      <div class="panel-body">	
	    <div class="form-group">
		  <%= label_tag :file, "File Upload (CSV only)", :class => 'control-label col-lg-3' %>
		  <div class="col-lg-5">
		    <%= file_field_tag :file,  :accept => 'text/csv', required: true %>
		  </div>
		</div>
	

		<div class="form-group">
	      <div class="col-lg-3"></div>
	      <div class="col-lg-3">
	        <%= button_tag type: "submit", :class => 'btn btn-info btn-fill' do %>
	            Upload
	        <% end %>
	      </div>
	    </div> 
      </div>
  	</div>

  <% end %>
  </div>
</div>